# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 
repository: "sg-moomin/sg-moomin.github.io" 

comments:
  provider: "utterances"
  utterances:
    theme: "github-light"
    issue_term: "pathname"

# Title of the Site
title: sg-moomin
# Description of the Site
description: 안녕하세요 세기무민입니다.
# URL of Image of the Site
# site-image: /WhatATheme/assets/images/meta.jpg
site-image: /
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/sg-moomin_main.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: rooney9325@gmail.com
# facebook_username: sg-moomin
# twitter_username: sg-moomin
instagram_username: sgmoomin
linkedin_username: sg-moomin
github_username:  sg-moomin
youtube_channel_id: UC-7QwSkVaVzcFQdJiStkVrg
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: sg-moomin

# Name of the Author
author-name: sg-moomin
# URL for the Image of the Author
author-image: /assets/images/20240601/20240601.png
# 60 Words About the Author
author-about: 현재 백앤드 개발자로 살아가고 있는 평범한 직장인 중 한명입니다.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/sg-moomin

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
